### PR TITLE
check delocate

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by mattip** [comment]
@isuruf do you need this merged or is it sufficient as a PR to test delocate?

**Comment by isuruf** [comment]
> @isuruf do you need this merged

Yes please. I tried using azure artifacts to  get the wheels from this PR, but couldn't get it to work.

**Comment by mattip** [comment]
Thanks @isuruf

**Comment by mattip** [comment]
Should I retrigger a build in order to use the new openblas for macos-arm64?

**Pull request merged**
