### PR TITLE
debug wheel renaming on windows

### PR DESCRIPTION
**Pull request by mattip**
fixes gh-90 

Done in this repo so the code is checked in the PR

### CODE REVIEW

**Comment by mattip** [comment]
It is hitting the renaming code, I wonder what is wrong with the sed command?

https://dev.azure.com/numpy/numpy/_build/results?buildId=9939&view=logs&j=2e1ef983-081d-5c63-b72a-d9f329364ee0&t=f86b9e5f-19fb-5cc9-4c85-984b7d9ccda4&l=15

**Comment by charris** [comment]
Are the right wheels being uploaded?
```
anaconda -t $TOKEN upload -u $ANACONDA_ORG numpy/dist/numpy-*.whl
```

**Comment by charris** [comment]
Also looks like some things are still being downloaded from rackspace, the gfortran libraries for one.

**Comment by mattip** [comment]
> Also looks like some things are still being downloaded from rackspace, the gfortran libraries for one

Where do you see that? That happens [for macos](https://github.com/MacPython/gfortran-install/blob/d430fe6e38b6c5149c53f775a4437964e2f7b883/gfortran_utils.sh#L85) but only if [the file here](https://github.com/MacPython/gfortran-install/tree/master/archives) cannot be found, which is why it is part of this repo

**Comment by mattip** [comment]
OK, I think that last commit was the problem. On windows the wheel directory is different, and I copy-pasted across from linux

**Comment by charris** [comment]
>Where do you see that?

I noticed the address in the raw log. Not sure the location is actually used.
```
2020-05-15T14:15:45.8197647Z ++ source gfortran-install/gfortran_utils.sh
2020-05-15T14:15:45.8198462Z +++ GF_LIB_URL=https://3f23b170c54c2533c070-1c8a9b3114517dc5fe17b7c3f8c63a43.ssl.cf2.rackcdn.com
2020-05-15T14:15:45.8199123Z +++ ARCHIVE_SDIR=archives
2020-05-15T14:15:45.8260558Z ++++ dirname gfortran-install/gfortran_utils.sh
```

**Comment by charris** [comment]
Seems to be the `function get_gf_lib_for_suf` in `gfortran_utils.sh`.

**Comment by charris** [comment]
Renaming seems to work, so merging after cleaning up the debugging should be OK.

**Comment by charris** [comment]
I cancelled the travis build, travis is clogged :(

**Comment by mattip** [comment]
Canceled the Travis build for the last commit

**Comment by charris** [comment]
LGTM, I'm just going to put it in. Thanks Matti.

**Pull request merged**
