### PR TITLE
[appveyor] build master

### PR DESCRIPTION
**Pull request by xoviat**
@charris This should build master, as requested.

Note: for a release build, I think we still need to bundle the UCRT dlls.

### CODE REVIEW

**Comment by xoviat** [comment]
@charris Questions?

**Comment by charris** [comment]
Hmm, why isn't daily building master?

**Comment by xoviat** [comment]
Daily *is* building master. But you said you wanted a master build, so that's what I did.

**Comment by charris** [comment]
And release builds are what we want to fix. I note that this didn't go through `window-wheels-builder`, which seems extreme as the fixes are local rather than global and that has been a problem. AFAIK, the daily builds have been working in any case, probably because they are still using the old mingwpy library.

**Comment by charris** [comment]
So what is the BUILD_COMMIT here?

**Comment by xoviat** [comment]
> probably because they are still using the old mingwpy library.

No, this worked *precisely because* is doesn't use mingw.

>  I note that this didn't go through window-wheels-builder

Yes. This is no surprise as I indicated that I would do this earlier. This build is almost a release build (aside from the fact that the version built isn't tagged). We just need to copy the UCRT DLLs and it should be releasable.

**Comment by xoviat** [comment]
Grep the build logs. No mingwpy in sight!

**Comment by charris** [comment]
But why aren't the daily builds building the master HEAD? The BUILD_COMMIT hash is really old.

**Comment by charris** [comment]
And if we change `appveyor.yml` in master in this way, won't backports become more difficult?

**Comment by xoviat** [comment]
They are! I still don't understand what you want to do. If you want to build 1.13.x, you can't use this build procedure, so you should branch from master and then I can help with fixing windows-wheel builder for 1.13.x. If you don't want to release any more maintenance wheels, then you should merge daily to master.

**Comment by charris** [comment]
What I would *like* to do is build both the 1.13.x branch and master. So I guess the thing to do to start things would be to create a `1.13.x` branch off master?

**Comment by xoviat** [comment]
That's probably the best option.

**Comment by charris** [comment]
OK, there is now a `v1.13.x` branch.

**Comment by charris** [comment]
So let's begin by fixing master. A merge will be a mess, so the simplest thing for me todo to start things off is to copy the `appveyor.yml`  file to master, fix it for the license, and push it. The `.travis.yml` in master is more current than the one in daily, so we might want to fix that also.

**Comment by xoviat** [comment]
The appveyor.yml for daily won't work for 1.13.x. I'm working on a fix for the wheel builder.

**Comment by charris** [comment]
OK, great. I've copied over appveyor from daily to master and pushed it. Let's see how it goes.

**Comment by xoviat** [comment]
So the problem is that I cannot copy addition DLLs that are required because of this line:

https://github.com/numpy/windows-wheel-builder/blob/bf6f454b1bc495ac8a3b9eb7e9751e7be445241e/build_numpy.py#L55

**Comment by xoviat** [comment]
Is there any way that you could remove that line from the windows wheel builder?

**Comment by charris** [comment]
Yes, I can do that, looks like we won't need this going forward in any case.  The submodule in numpy-wheels will need an update after. Do you know how to do that?

**Comment by xoviat** [comment]
Yes I do, but it would make my life easier if you pushed the changes to 1.13.x

**Comment by charris** [comment]
OK,  line removed and pushed.

**Comment by charris** [comment]
Which changes?

**Comment by xoviat** [comment]
The submodule update

**Comment by charris** [comment]
OK, although you can also do it in the PR which should be simpler.

**Comment by xoviat** [comment]
Actually, I could work around that...

**Comment by charris** [comment]
Done anyway. You may need to rebase.

**Comment by charris** [comment]
When you say "bundle DLL's", do you mean in the wheels so that other projects can use them? Wasn't that discussed for SciPy when the licensing issue came up?

**Comment by xoviat** [comment]
We need to include the mingw DLLs because we are using the MSVC ABI. AFAIK mingw has no problems with licensing. If that's not correct, then we're in trouble.

**Comment by xoviat** [comment]
#12 should fix the problem but of course the file permissions are wrong.

**Comment by charris** [comment]
How does SciPy do it?

**Comment by xoviat** [comment]
Scipy uses the MinGW ABI, which doesn't have these issues.

**Comment by charris** [comment]
Ah, so they are only needed for v1.13.x?

**Comment by xoviat** [comment]
Correct.

**Comment by charris** [comment]
Hmm, no DLL confusion possible?  I assume tests work now because of the appveyor environment?

**Comment by xoviat** [comment]
Is choelsky tested?

**Comment by xoviat** [comment]
If so, then let's just leave it be.

**Comment by charris** [comment]
Yes, the test was backported.

**Comment by xoviat** [comment]
FYI the mingwpy builds don't require the DLLs but I assumed they were broken.

**Comment by charris** [comment]
Note that for numpy, the wheels builds succeed even if the tests fail ;) Needs fixing. Anyway, you can check the test results from the build.

**Comment by charris** [comment]
The mingwpy builds worked, except for the cholesky test on 32 bit windows. Oh, and a couple of other failing tests from the backports that need fixing up.

**Comment by charris** [comment]
If things look too messy we can give up on the 1.13.4 release. It was update that might have been useful to distributions out of sync with numpy releases, but I will be branching 1.14 real soon now.

**Comment by charris** [comment]
I'm going to sign off for the night, see you tomorrow :)

**Comment by xoviat** [comment]
Hopefully my distutils PRs will make it in. :)

**Pull request closed without merging**
