### PR TITLE
drop python3.6, add pypy3.7

### PR DESCRIPTION
**Pull request by mattip**
drop python 3.6
add pypy3.7

### CODE REVIEW

**Comment by mattip** [comment]
The failures are the known 32-bit ones, should be fixed now on master after merging numpy/numpy#16247

**Comment by rgommers** [comment]
The new PyPy job timed out at 60% of the test suite after an hour.

Also, the comments in `.travisci.yml` for other PyPy issues are no longer relevant? Or is that tracked elsewhere?

**Comment by mattip** [comment]
The comments were for macOSx and arm64 builds of PyPy. Both those issues were fixed in subsequent releases, but I am not proposing NumPy release wheels for those versions (yet).

As for the time-out, it seems something is off. The last run [on travis of pypy3.6-7.3.1](https://travis-ci.com/github/MacPython/numpy-wheels/jobs/422095426) took 30 minutes (as did the arm64 runs).

**Comment by mattip** [comment]
Close/Reopen to rebuild off master

**Comment by mattip** [comment]
CI is green, the PyPy run takes ~35 minutes vs. ~10 minutes on macOSx, linux and ~15-25 on windows.

**Comment by charris** [comment]
Thanks Matti.

**Pull request merged**
