### PR TITLE
MAINT: Try making 3.10 wheels on Windows and OSX

### PR DESCRIPTION
**Pull request by charris**

### CODE REVIEW

**Comment by charris** [comment]
Two things are new with the 3.10 release

- Microsoft will be dropping 32 bit Python 3.10 and is not available on azure-pipelines
- The Mac version is only available as a universal2 wheel. That is due to Multibuild requiring osx 11+ for the build.

**Comment by mattip** [comment]
I wonder if cibuildwheel + github actions will be any different.

**Comment by mattip** [comment]
For 32-bit windows wheels, if all else fails we might be able to use a 32-bit docker container image, and then run it via a [container](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=example%2Cparameter-schema#container-resource)

**Comment by mattip** [comment]
It seems cibuildwheel has 32-bit windows, see [the table of supported versions](https://cibuildwheel.readthedocs.io/en/latest/options/#build-skip)

**Comment by charris** [comment]
@mattip, the omission of 32 bit Python 3.10 on windows was a deliberate choice of the azure folks. We could probably talk them into it, but if Microsoft is headed that way, we might want to go along. The bigger problem is that travis-ci has become completely unreliable for arm64, mostly timeouts on fetches and downloads. I don't know the cause, but is a PITA.

**Comment by charris** [comment]
@matthew-brett See https://github.com/actions/virtual-environments/issues/4226#issuecomment-945097662. I do have a question about multibuild, it won't build Python 3.10 wheels for x86_64, only for arm64 and universal2 wheels. I'm not sure if those wheels work correctly. I think this is due to line 168 in osx_utils.sh.  Maybe the mac version number needs an update to `macosx_11_0`?

**Pull request merged**
