### PR TITLE
set MB_PYTHON_OSX_VER=10.9

### LINKED ISSUE #43: macOS wheel naming incorrectly includes 10.6
See https://github.com/numpy/numpy/issues/12939

### PR DESCRIPTION
**Pull request by mattip**
Fixes #43 

need to check that the artifact name in fact does not contain macosx_10_6_intel

### CODE REVIEW

**Comment by mattip** [comment]
Anyone understand what is wrong with the [macOS CI run](https://travis-ci.org/MacPython/numpy-wheels/jobs/575245483) ?

**Comment by charris** [comment]
@matti MacPython/numpy-wheels appveyor pipeline is completely stuffed up and stalled with junk builds. I don't have the permission to cancel, but it looks like you do. Could you clean it up? And do your work in a branch.

**Comment by mattip** [comment]
@charris I do not see how to cancel those. Maybe @matthew-brett can? The work is on a branch, I guess I should remove the appveyor/travis builds from #60 until it is ready to build

**Comment by matti** [comment]
@charris please ping @mattip who has also awesome github name

**Comment by charris** [comment]
@mattip Guess we will need to wait on @matthew-brett. Guess this is one more reason to move things to the NumPy project and implement azure-pipelines :)

**Comment by charris** [comment]
We should also ask Matthew to add us to the numpy-wheels account on appveyor.

**Comment by charris** [comment]
OK, this looks fixed, but I think it required this change to `config.sh`
```
diff --git a/config.sh b/config.sh
index 645008b..0329262 100644
--- a/config.sh
+++ b/config.sh
@@ -15,7 +15,14 @@ function build_wheel {
 
 function build_libs {
     local plat=${1:-$PLAT}
-    local tar_path=$(abspath $(get_gf_lib "openblas-${OPENBLAS_VERSION}" "$plat"))
+    # Force 64-bit OpenBLAS library for macOS intel (dual arch)
+    # builds. For these builds, we pretend to be dual arch, but in
+    # fact we're only using the 64-bit build of OpenBLAS
+    if [ -n $IS_OSX ] && [ $plat == intel ]; then
+        plat=x86_64
+    fi
+    local tar_fname=$(get_gf_lib "openblas-${OPENBLAS_VERSION}" "$plat")
+    local tar_path=$(abspath $tar_fname)
     # Sudo needed for macOS
     local use_sudo=""
     [ -n "$IS_OSX" ] && use_sudo="sudo"
```
@matthew-brett I thought that was a temporary workaround?

**Comment by charris** [comment]
Still broken. I think it is due to requiring xcode 6.4 and picked up from the environment.

**Comment by charris** [comment]
try close.

**Comment by charris** [comment]
@mattip I notice that the release was built on my own appveyor account but can't be uploaded without a Rackspace API key.
```
            # This is for Rackspace uploads.  Contact Matthew Brett, or the
            # scikit-learn team, for # permission (and the API key) to upload to
            # the Rackspace account used here, or use your own account.
```
So if @matthew-brett doesn't show up soon and we can't get the stalled process canceled in some other way, we might want to look into getting the API key from someone else or uploading to a different repository. I guess using a different repo would require hand downloading, although I'd have to check the downloader to be sure.

**Comment by charris** [comment]
Hmm, we have the key, so the trick is to figure out why some pushes trigger uploads while others don't.

**Comment by mattip** [comment]
[This build](https://ci.appveyor.com/project/matthew-brett/numpy-wheels/builds/26881687) has been going for 76 hours. I think it is what is holding up the [pipeline](https://ci.appveyor.com/project/matthew-brett/numpy-wheels/history).

**Comment by charris** [comment]
Maybe try deleting the azure app?

**Comment by charris** [comment]
> This build has been going for 76 hours.

I noticed :) However, I'm trying to figure out how to get my personal appveyor account to upload the result, it builds and tests...

**Comment by charris** [comment]
@mattip Mind if I delete the azure app?

**Comment by charris** [comment]
Hmm, there is no delete button for azure, maybe I don't have permissions. Can you take a look?

**Comment by charris** [comment]
Could be that the azure app configuration was never finished.

**Comment by charris** [comment]
What is the azure account? Who has permissions?

**Comment by mattip** [comment]
I connected this repo to azure using [this page](https://github.com/MacPython/numpy-wheels/settings/installations). Can you see it?

**Comment by charris** [comment]
@mattip If you look at the numpy one, it has a remove button and the numpy-wheels one doesn't. I removed and added the numpy azure app several times during the spin up, so it may be a permissions thing, I notice that our permissions for numpy-wheels are just for a couple of repos, while the azure app potentially covers all of MacPython, so there is that. IIRC, one of the owners (me) needed to install it on numpy.

I'm now curious about where the pipeline is on azure and if you have access to it. For appveyor I think Matthew would need to add us to his project. If Mathew doesn't respond soon, we may be able to contact the appveyor admins and get it shut down, although since we don't have permissions on the account that may be difficult. ISTR doing that many years ago for NumPy.

Another curiosity is that there are three different appveyor hooks, and all of them seem active. Not sure what that is about, maybe different triggers/post test environments. But without the appropriate permissions on the appveyor account I cannot tell much about how they are set up.

**Comment by charris** [comment]
I think this does indicate that we would be better off if the wheels builds were transferred to NumPy.

**Comment by charris** [comment]
Note that because the azure app in numpy already covers all the repos, we probably just need to add a pipeline on the azure end. So that much should be easy.

**Comment by matthew-brett** [comment]
Hi - sorry - got swamped with social things at the weekend.  Is there
anything I need to do?

**Comment by mattip** [comment]
@matthew-brett  Can you kill appveyor CI runs? [This one](https://ci.appveyor.com/project/matthew-brett/numpy-wheels/builds/26881687) seems hung for quite a while. Assuming you can, is there any way to share that super power so others can also cancel jobs?

**Comment by matthew-brett** [comment]
Hi,

I think I killed that one.

Do you know how I can share per-repository permissions on Appveyor?  Sorry,
I seem to remember that's rather difficult.  Maybe it would be better to
set up a Numpy appveyor thing with team permissions?

Cheers,

Matthew

**Comment by charris** [comment]
> Maybe it would be better to set up a Numpy appveyor thing with team permissions?

NumPy was running tests on my appveyor account. IIRC, we were unable to set up a project account at the time, but maybe that is possible these days. IIRC, I could add others to my account.

**Comment by matthew-brett** [comment]
Hi,

It means they were built with Pythons from the older Python 10.6-compatible
installer, and that claims that they are compatible with any Mac with macOS
version >= 10.6.

But I think, from env_vars.sh - that these are only compatible with macOS
>= 10.9.

So, they should probably be renamed accordingly, to avoid confusion.

Cheers,

Matthew

**Comment by matthew-brett** [comment]
I think that, when the code is compiled it has the following defined, from
`env_vars.sh`:

MACOSX_DEPLOYMENT_TARGET=10.9

Hence, I think the resulting code is compatible only with macOS >= 10.9.
The wheel filename, meanwhile, comes from the Python binary used for the
distutils call.

Cheers,

Matthew

**Comment by mattip** [comment]
@charris are we ready to retry this? It would be nice to get the correct wheel names

**Comment by charris** [comment]
It is already done. 10_6 for 1.17.2 and 10_9 for 1.18.

**Pull request closed without merging**
