### PR TITLE
Append flags

### PR DESCRIPTION
**Pull request by mattip**
Replaces gh-82 : we should strip the linux binaries before shipping. 

Issue gh-19 assumed that we do not override CFLAGS, but we do. Using a branch on a fork so successful builds are not uploaded

### CODE REVIEW

**Comment by charris** [comment]
Thanks Matti. There were no uploads, so that worked. Should we add back the `-msse2` flags?

**Comment by mattip** [comment]
> Should we add back the -msse2 flag

OK.

**Comment by mattip** [comment]
Hmm, it didn't work. The [file sizes](https://anaconda.org/scipy-wheels-nightly/numpy/files)  are the same.

**Comment by charris** [comment]
Looks like the manylinux2010 files are a lot bigger than manylinux1 files. Do they have an extra fortran library?

**Comment by charris** [comment]
There is no OpenBLAS in the manylinux1 wheels.

**Comment by charris** [comment]
Maybe we need to strip the OpenBLAS libraries. Do we want to do that?

**Comment by mattip** [comment]
> There is no OpenBLAS in the manylinux1 wheels.

Whoops. numpy/numpy#16171

**Comment by mattip** [comment]
> Maybe we need to strip the OpenBLAS libraries. Do we want to do that?

I think they are pretty good. `strip -g` didn't remove anything, `strip -s` reduced the 18.3 one from 29 to 28MB.

**Pull request merged**
