### PR TITLE
Add python3.7 builds

### PR DESCRIPTION
**Pull request by ngoldbaum**
@charris assuming this builds it would be great if you could upload python3.7 wheels.

### CODE REVIEW

**Comment by ngoldbaum** [comment]
yay it builds :)

@matthew-brett or @charris would you be ok with merging this or do you want to wait to support python3.7 until the numpy 1.5 release?

**Comment by matthew-brett** [comment]
We should definitely make wheels as soon as possible, but I think Appveyor is still using Python 3.6 for the 3.7 builds.  As far as I know, Appyevor does not have Python 3.7 yet.

**Comment by ngoldbaum** [comment]
> ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%
> C:\Python36 3.7 32

Ah indeed thanks for pointing that out.

https://github.com/appveyor/ci/issues/2475

I guess we'll wait until next week.

**Comment by matthew-brett** [comment]
I built and uploaded Windows wheels, just trying to get Linux / macOS builds out now.

**Comment by matthew-brett** [comment]
OK, uploaded manylinux and macOS build as well.  Python 3.7 should be wheeled up.

**Comment by charris** [comment]
@matthew-brett What is the best way to proceed with 1.15.0rc2? It sounds like you are special buitding the 3.7 wheels for now. I'm also curious about the schedule for renaming the windows wheels.

**Comment by matthew-brett** [comment]
I made some new build entries in the 1.14.x branch, and added a few fixes to deal with various things, including the missing Python 3.7 installer on Appeveyor:

https://github.com/MacPython/numpy-wheels/tree/v1.14.x

I had to do a branch of that branch to disable the tests for the few warnings tests that were failing.

I've just merged the v1.14.x branch into master, so that should be ready to branch for the 1.15 series.

By "renaming the windows wheels" you mean, giving the full API tags, instead of the current `numpy-1.14.5-cp37-none-win32.whl` pattern, with `none` as the second entry.   The `none` comes about by deliberately downgrading wheel during the build process, in order to make the wheels compatible with older pip.  I'm guessing that almost everyone has old-enough pip now, so we can give up on that fix, but I don't have the pip version share or the first acceptable version to hand.

**Comment by charris** [comment]
@matthew-brett 1.15 was already branched, you probably need to pull it. I'll look to update it from master.

**Comment by charris** [comment]
Any reason you didn't update the global `CYTHON_BUILD_DEP` to `0.28.2`?

**Comment by matthew-brett** [comment]
No reason - in the 1.14.x builds I left the Cython dependency as was, and let the Python 3.7 dependency be simply `Cython`.

**Comment by charris** [comment]
OK, I just rebranch, that looks like the easiest thing to do.

**Comment by charris** [comment]
> but I don't have the pip version share or the first acceptable version to hand.

Not a pressing problem, so no need to rush.

**Pull request closed without merging**
