### PR TITLE
MAINT: Add license texts for bundled libraries.

### PR DESCRIPTION
**Pull request by charris**
Pretty much a straight copy of @pv's corresponding PR for `scipy-wheels`, https://github.com/MacPython/scipy-wheels/pull/5 .

### CODE REVIEW

**Comment by charris** [comment]
@matthew-brett This includes DLLs (gfortran) on windows. Do we make any use those DLLs for NumPy?

**Comment by matthew-brett** [comment]
I guess we do make use of them - but I'm not up to date with our Windows builds - @xoviat @pv ?

**Comment by xoviat** [comment]
Yes, the GCC runtime libraries are used for OpenBLAS.

**Comment by pv** [comment]
The master branch of this repository that this PR is against, however doesn't have the openblas setup which is only in the `daily` branch (cf https://github.com/MacPython/scipy-wheels/issues/19).

**Comment by charris** [comment]
> The master branch of this repository that this PR is against, however doesn't have the openblas setup which is only in the daily branch

@matthew-brett  Aren't all NumPy builds in windows and linux using openblas these days? Oh, and what is the status of the openblas bug on windows 32 bit?

**Comment by charris** [comment]
Keeping minimal changes here, adding license files, and opened issues for remaining problems to be fixed in later PRs. Will commit as soon as tests pass. Note that this uses the old OpenBLAS build with resulting test failure on master, but that failure is not currently detected in the builds.

**Pull request merged**
