### PR TITLE
Use Azure Pipelines and upload to anaconda

### PR DESCRIPTION
**Pull request by mattip**
Copy the pandas-wheels approach of using Azure and uploading to anaconda

### CODE REVIEW

**Comment by charris** [comment]
Progress!

**Comment by charris** [comment]
The windows wheels seem to be 1.18.2?

**Comment by mattip** [comment]
Yes, since the build tag is 1.18.2
Still todo: 
- fix the openblas windows linking
- use tokens to upload to anaconda

**Comment by tylerjereddy** [comment]
Hey Matti--you're an owner of the appropriate anaconda.org group now

**Comment by mattip** [comment]
@tylerjereddy thanks. I added a [NUMPY_STAGING_UPLOAD_TOKEN secret](https://github.com/MacPython/numpy-wheels/settings/secrets) to this repo, which I got from [the multibuild-wheels-staging group](https://anaconda.org/multibuild-wheels-staging/settings/access), but `anaconda upload` is failing. Any ideas? Is there a way to get more info from the anaconda client?

<Details><summary>log of the upload</summary>

```
numpy/dist/numpy-1.19.0.dev0+9eb7560-cp36-cp36m-win_amd64.whl
Using Anaconda API: https://api.anaconda.org
Using "multibuild-wheels-staging" as upload username
Processing 'numpy/dist/numpy-1.19.0.dev0+9eb7560-cp36-cp36m-win_amd64.whl'
Detecting file type...
File type is "pypi"
Extracting python package attributes for upload
Creating package "numpy"

##[error]Bash exited with code '1'.
```

**Comment by mattip** [comment]
I can run `anaconda -t $SECRET upload -u multibuild-wheels-staging numpy/dist/numpy*.whl` from the command line, so something must be off with the script I copied from pandas-wheels. Adding some debug in c0a3da2

**Comment by mattip** [comment]
Hah, the $TOKEN starts with "$(N", not the contents of the secret.

**Comment by mattip** [comment]
Maybe the problem is I added the secrets to the repo, not the azure pipeline.

**Comment by mattip** [comment]
[Success!!!](https://anaconda.org/multibuild-wheels-staging/numpy/files). Let's see if I can get 1.18.3 releases onto that site, and I will remove the 1.19 pre-releases, they belong in the https://anaconda.org/scipy-wheels-nightly/ directory

**Comment by mattip** [comment]
Making one more commit, that I will back out, to test the nightly cron job and that linux32 passes on master HEAD.

**Comment by charris** [comment]
@mattip are you sure this should be merged? There are still the 32bit linux failures which look like failure it install OpenBLAS

**Comment by mattip** [comment]
> There are still the 32bit linux failures 

Those are due to the v1.18.3 tag and some incompatibility with the uname Azure reports for the 32-bit build here vs. the uname it reports on numpy/numpy. The openblas_support.py is more robust on the master branch so it all passes, as you can see at both the `https://anaconda.org/multibuild-wheels-staging` (which are the pre-release wheels) and the `https://anaconda.org/scipy-wheels-nightly/numpy/files` (which are the weekly wheels built off HEAD).

**Comment by charris** [comment]
Thanks Matti.

**Comment by charris** [comment]
`.appveyor.yml` still exists, should it be removed?

**Comment by mattip** [comment]
Unlike travis, appveyor errors out if there is no .appveyor.yml so I had to add an empty one.

**Comment by charris** [comment]
The appveyor hook can be disabled in the settings,  I'll do that.

**Comment by charris** [comment]
I've disabled all the webhooks for appveyor and travis.

**Comment by charris** [comment]
There were three for appveyor and I deleted the failing one, which is probably the one I should have kept. Oh well...

**Pull request merged**
