### PR TITLE
Pypy rc1

### PR DESCRIPTION
**Pull request by mattip**
- use pypy 7.3.4rc1 to get METH_FASTCALL. It should be officially released by the time we release 1.21
- add `--skip` to avoid anaconda upload errors

### CODE REVIEW

**Comment by mattip** [comment]
@charris I think `--skip` is preferable over `--force`: you can always make a dummy commit to numpy to change the hash and then trigger a build here. I think it would be more confusing to replace versions that were already uploaded.

**Comment by charris** [comment]
skip is fine, the uploads of duplicates currently errors. I note that 7.3.4 is out now, according to the pypy site.

**Comment by mattip** [comment]
> I note that 7.3.4 is out now, according to the pypy site.

The first release candidate  for 7.3.4 is out, but it has not been officially released yet.

**Comment by charris** [comment]
Thanks Matti.

**Pull request merged**
