### PR TITLE
update multibuild and appveyor to Python3.8.0 final

### PR DESCRIPTION
**Pull request by mattip**
Python 3.8 was released and multibuild (and manylinux) support it. Upgrade to it.

### CODE REVIEW

**Comment by charris** [comment]
@mattip,  @seberg needs to fix a test before master will pass. He has been notified.

**Comment by seberg** [comment]
We fixed that this morning (I hope), so lets see...

**Comment by charris** [comment]
@seberg it is still failing...

**Comment by mattip** [comment]
Why is the numpy repo [pegged to 83da5faca](https://travis-ci.org/MacPython/numpy-wheels/jobs/598322599#L546) which is the master from last night? Shouldn't it be using latest master?

**Comment by mattip** [comment]
Appveyor is getting the same stale version, not clear how. Maybe @matthew-brett has clue?

**Comment by mattip** [comment]
it seems at least the [first build](https://travis-ci.org/MacPython/numpy-wheels/jobs/598365055#L546) got the correct HEAD for numpy master

**Comment by charris** [comment]
Don't spend too much time on it today, I need to get the release built, and that also tests the Python 3.8 release.

**Comment by charris** [comment]
@mattip The windows builds are failing because Python3.8 is neither available nor downloaded and installed. There must have been a special path for Python3.8rc1 that caused it to be installed.

**Comment by charris** [comment]
Looks like appveyor is slow to catch up on these things.

**Comment by charris** [comment]
For some reason the windows python3.8 build defaults to python2.7. I think appveyor does have python3.8.0b4 installed, so that may be part of the problem.

**Comment by mattip** [comment]
there was a problem with the script that was meant to download windows versions if the are not available.

**Comment by mattip** [comment]
If you would like to move this forward, you could commit the changes in matthew-brett/multibuild#271 to this repo without waiting for an official update

**Comment by charris** [comment]
@mattip I'll wait, would rather finish the release in the morning (my time) than hang out all evening :)

**Comment by charris** [comment]
I went ahead and pushed fixes directly to master to triggers pre-release builds, so closing this. Thanks Matti.

**Pull request closed without merging**
